In [1]:
import numpy as np
import sys
print(sys.version)
print(np.version.version)

## use this site to get more numpy practise problems
## https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/

3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
1.21.5


In [2]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

print(a*b)

[ 4 10 18 28 40]


In [3]:
x = np.array([[1,2,3],[1,2,3]])

In [4]:
print(a.ndim)
print(x.ndim)

1
2


In [5]:
print(a.shape)
print(x.shape)

(5,)
(2, 3)


#### convert data type reverse the numpy array

In [6]:
input = np.array([1,2,3,4,-8,-10]);
print(input)
## reverse the array
output = input[::-1]
##output = output.astype(float)
print(output)
#now change the input and see if its reflecting in output
input[5] = 100

print("Test by changing the input and see if its reflecting in output")

print(input)
print(output)

[  1   2   3   4  -8 -10]
[-10  -8   4   3   2   1]
Test by changing the input and see if its reflecting in output
[  1   2   3   4  -8 100]
[100  -8   4   3   2   1]


#### Reshape the numpy array

In [7]:
input = np.array([1,2,3,4,5,6,7,8,9])
output = np.reshape(input,(3,3))
print(output)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Transpose and flatten array

In [8]:
#### Transpose array
input = np.array([[1,2,3],[4,5,6],[7,8,9]])
output = np.transpose(input)
print("*** transposed array *** ")
print(output)
print("*** transposed and flattened array *** ")
output = output.flatten
print(output)

*** transposed array *** 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
*** transposed and flattened array *** 
<built-in method flatten of numpy.ndarray object at 0x000000E4D78097B0>


In [9]:
#### zeros and ones 

In [10]:
zeros = np.zeros([2,3])
print(zeros)
ones = np.ones([3,5])
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Basic maths

In [11]:
## Add
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print("**** add 1d array \n")
print(a+b)
print(np.add(a,b))

print("\n **** add 2d array \n")
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
y = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(np.add(x,y))

## sum of array in given axis
a = np.array([[1,2,3],[5,6,7],[8,9,10]])
print("\n **** sum of matrix on axis \n")
print(np.sum(a,0))
print(np.sum(a,1))


print("\n **** 3d array \n")
a = np.arange(24)
##create a 3d array of axis - 2,3,4.
##it  is simlar to having two 3x4 matrices together
a = a.reshape(2,3,4)

##print first matrix in 3d array
print("\n **** first grid of 3d array \n")
print(a[0])

print("\n **** second grid of 3d array \n")
print(a[1])

print("\n **** sum of first and second grid of 3d array \n")
print(a[0]+a[1])

print("\n **** 4d array \n")
a = np.arange(48)
##create a 4d array of axis - 2,2,3,4.
##it is simlar to having two 3d array which is again two 2d array of 3x4 matrices together
a = a.reshape(2,2,3,4)

##print first matrix in 3d array
print("\n **** first grid of 4d array \n")
print(a[0][0])
print(a[0][1])

print("\n **** second grid of 4d array \n")
print(a[1][0])



**** add 1d array 

[ 7  9 11 13 15]
[ 7  9 11 13 15]

 **** add 2d array 

[[ 7  9 11 13 15]
 [ 7  9 11 13 15]]

 **** sum of matrix on axis 

[14 17 20]
[ 6 18 27]

 **** 3d array 


 **** first grid of 3d array 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 **** second grid of 3d array 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

 **** sum of first and second grid of 3d array 

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

 **** 4d array 


 **** first grid of 4d array 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

 **** second grid of 4d array 

[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


#### leet code problem with arrays to practise numpy
There is a row of n houses, where each house can be painted one of three colors: red, blue, or green. The cost of painting each house with a certain color is different. You have to paint all the houses such that no two adjacent houses have the same color.The cost of painting each house with a certain color is represented by an n x 3 cost matrix costs.

If the given array is — {17, 2, 1}, {16, 16, 1}, {14, 3, 19}, {3, 1, 8}
then minimum cost of painting is 2 + 1 + 3 + 3 = 9

In [13]:
##Start from second house
def minCost(input):
    result = np.zeros(input.shape)
    nHouse = input.shape[0]
    nCost = input.shape[1]
    result[0] = input[0]

    for i in range(1, nHouse):
        for j in range(0, nCost):
            if(j == 0):
                result[i][j] = (input[i][j] + result[i-1][j+1])
            if(j == nCost-1):
                result[i][j] = (input[i][j] + result[i-1][j-1])
            else:
                result[i][j] = min((input[i][j] + result[i-1][j+1]), (input[i][j] + result[i-1][j-1]))
    print(np.min(result[nHouse-1]))

In [15]:
input = np.array([[17,2,1],[16,16,1],[14,3,19],[3,1,8]])
minCost(input)
input = np.array([[14, 2, 11],[11, 14, 5],[14, 3, 10]])
minCost(input)

9.0
10.0
